### ISSUE TITLE
double-conversion doesn't properly export its symbols

### ISSUE THREAD

**Issue by SpaceIm** [google/double-conversion#139]
https://github.com/google/double-conversion/pull/136 added `WINDOWS_EXPORT_ALL_SYMBOLS` to CMake build as a workaround  for shared build with Visual Studio.

Problems:
- `WINDOWS_EXPORT_ALL_SYMBOLS` is bad practice, it should be considered as a temporary workaround.
- double-conversion has a lot of static member functions, `WINDOWS_EXPORT_ALL_SYMBOLS` can't export these ones, leading to `unresolved external symbol` errors (in `Qt5Core` build for example if `double-conversion` is shared).

To properly export symbols for Visual Studio, `declspec(dllexport)` and `declspec(dllexport)` should be used, no choice.

EDIT: I need to double check :grimacing:

**Comment by SpaceIm** [comment]
Did not checkout commit including #136 commit :sweat:

Seems to work with `WINDOWS_EXPORT_ALL_SYMBOLS`. I close this issue.

**Comment by floitsch** [comment]
No problem. Hadn't started looking into it yet.
Thanks for the follow-up. (I wouldn't have remembered the `WINDOWS_EXPORT_ALL_SYMBOLS` PR).

**Comment by SpaceIm** [comment]
`CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` doesn't export global data symbols, but exports static member function (I was wrong), so it's fine.

https://cmake.org/cmake/help/latest/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html
